[profile.default]
src = "../contracts"
out = "../out"
libs = ["../lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

[etherscan]
sepolia = { key = "${ETHERSCAN_API}" }

# TODO: add invariant and fuzz configs when migrating the dry-run contracts into production scope.
